baseURL = 'http://docs.noiseroute.com/'
languageCode = 'en-us'
title = 'Noise Route Docs'
theme = 'hugo-geekdoc'

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
[markup.goldmark.renderer]
# Needed for mermaid shortcode
unsafe = true
[markup.tableOfContents]
startLevel = 1
endLevel = 9

[taxonomies]
tag = "tags"

[params]
geekdocLogo = "noise-route.svg"
geekdocRepo = "https://github.com/NoiseRoute/docs"
geekdocEditPath = "/tree/master/"
geekdocMenuBundle = true
